name: verifastscore
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - catalogue=2.0.10
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.4
  - cymem=2.0.6
  - cython-blis=1.0.1
  - datasets=3.3.2
  - dill=0.3.8
  - frozenlist=1.5.0
  - huggingface_hub=0.29.2
  - icu=73.1
  - idna=3.7
  - langcodes=3.3.0
  - libcurl=8.12.1
  - libffi=3.4.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - murmurhash=1.0.12
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openssl=3.0.16
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - preshed=3.0.8
  - propcache=0.3.1
  - protobuf=5.29.3
  - pyarrow=19.0.0
  - pygments=2.19.1
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - safetensors=0.5.3
  - setuptools=78.1.1
  - shellingham=1.5.0
  - six=1.17.0
  - smart_open=5.2.1
  - snappy=1.2.1
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.5.1
  - thinc=8.3.2
  - tk=8.6.14
  - tokenizers=0.21.0
  - tqdm=4.67.1
  - transformers=4.49.0
  - typer=0.9.0
  - typing-extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wasabi=0.9.1
  - weasel=0.3.4
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - deepspeed==0.16.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - jiter==0.9.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numpy==1.26.3
      - nvidia-ml-py==12.575.51
      - openai==1.77.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.13.3
      - typing-inspection==0.4.0
      - zipp==3.21.0
